
all:
	$(MAKE) -C test_stiffness all
	$(MAKE) -C test_strength all
	$(MAKE) -C test_loading all
	$(MAKE) -C test_noheat all
	$(MAKE) -C test_singlecell all

clean:
	$(MAKE) -C test_stiffness clean
	$(MAKE) -C test_strength clean
	$(MAKE) -C test_loading clean
	$(MAKE) -C test_noheat clean
	$(MAKE) -C test_singlecell clean
