function Units = si_units

% Define units relative to SI units
Units = struct(...
    'yr', 365.25*24*3600,...
    'day', 24*3600, ...
    'hr', 3600, ...
    'min', 60, ...
    's', 1, ...
    'GPa', 1e9, ...
    'MPa', 1e6, ...
    'km', 1e3, ...
    'm', 1, ...
    'cm', 1e-2, ...
    'mm', 1e-3, ...
    'kJ', 1e3, ...
    'J', 1, ...
    'K', 1, ... % Kelvin
    'kg', 1, ...
    'g', 1e-3 ); % gram
end